/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_HelloNative */

#ifndef _Included_hello_HelloNative
#define _Included_hello_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_HelloNative
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_HelloNative_printHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
