/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_UseCPP */

#ifndef _Included_hello_UseCPP
#define _Included_hello_UseCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_UseCPP
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_UseCPP_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
