/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_HelloNative2 */

#ifndef _Included_hello_HelloNative2
#define _Included_hello_HelloNative2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_HelloNative2
 * Method:    printHello2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_HelloNative2_printHello2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
