/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class operation_OperateNumber */

#ifndef _Included_operation_OperateNumber
#define _Included_operation_OperateNumber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     operation_OperateNumber
 * Method:    numberAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_operation_OperateNumber_numberAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     operation_OperateNumber
 * Method:    testIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_operation_OperateNumber_testIntArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
