/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class operation_OperateString */

#ifndef _Included_operation_OperateString
#define _Included_operation_OperateString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     operation_OperateString
 * Method:    stringCopy
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_operation_OperateString_stringCopy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     operation_OperateString
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_operation_OperateString_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     operation_OperateString
 * Method:    sayHello2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_operation_OperateString_sayHello2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
