/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sort_AdvancedSort */

#ifndef _Included_sort_AdvancedSort
#define _Included_sort_AdvancedSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sort_AdvancedSort
 * Method:    mergeSort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sort_AdvancedSort_mergeSort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     sort_AdvancedSort
 * Method:    quickSort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sort_AdvancedSort_quickSort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     sort_AdvancedSort
 * Method:    shellSort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sort_AdvancedSort_shellSort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
