/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sort_NumberSort */

#ifndef _Included_sort_NumberSort
#define _Included_sort_NumberSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sort_NumberSort
 * Method:    DirectInsertion
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sort_NumberSort_DirectInsertion
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     sort_NumberSort
 * Method:    SimpleSelection
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sort_NumberSort_SimpleSelection
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     sort_NumberSort
 * Method:    bubble
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sort_NumberSort_bubble
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
